name: Workflow Run
on:
  workflow_run:
    workflows: ["events"]
    types: 
      - completed
jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - name: This is testing of WF dependednt
        run: echo "This Workflow was triggered because 'Repository Events WorkFLOW' was completed"